te_platform_homepage:
    path:     /
    defaults: { _controller: TEPlatformBundle:Lift:index }

te_lift_add:
    path:     /lift/add
    defaults: { _controller: TEPlatformBundle:Lift:add }

te_lift_edit:
    path:     /lift/edit/{id}
    defaults: { _controller: TEPlatformBundle:Lift:edit }
    requirements:
      id:   \d

te_lift_remove:
    path:     /lift/remove/{id}
    defaults: { _controller: TEPlatformBundle:Lift:remove }
    requirements:
      id:   \d

te_lift_view:
  path: /lift/view/{id}
  defaults: { _controller: TEPlatformBundle:Lift:view }

te_booked_subscribe:
  path: /booked/subscribe/{id}
  defaults: { _controller: TEPlatformBundle:Lift:subscribe }

te_booked_unsubscribe:
  path: /booked/unsubscribe/{id}
  defaults: { _controller: TEPlatformBundle:Lift:unsubscribe }
