te_platform_homepage:
  path:     /
  defaults: { _controller: TEPlatformBundle:Lift:index }

te_lift_search:
  path: /lift/search
  defaults: { _controller: TEPlatformBundle:Lift:search }

te_lift_add:
  path:     /lift/add
  defaults: { _controller: TEPlatformBundle:Lift:add }

te_lift_edit:
  path:     /lift/edit/{id}
  defaults: { _controller: TEPlatformBundle:Lift:edit }
  requirements:
    id:   \d

te_lift_remove:
  path:     /lift/remove/{id}
  defaults: { _controller: TEPlatformBundle:Lift:remove }
  requirements:
    id:   \d

te_lift_view:
  path: /lift/view/{id}
  defaults: { _controller: TEPlatformBundle:Lift:view }

te_booked_subscribe:
  path: /booked/subscribe/{id}
  defaults: { _controller: TEPlatformBundle:Lift:subscribe }

te_booked_unsubscribe:
  path: /booked/unsubscribe/{id}
  defaults: { _controller: TEPlatformBundle:Lift:unsubscribe }

te_eval_positive:
  path: /eval/positive/{id}
  defaults: { _controller: TEPlatformBundle:Lift:positive }

te_eval_negative:
  path: /eval/negative/{id}
  defaults: { _controller: TEPlatformBundle:Lift:negative }

te_user_register:
  path: /user/register
  defaults: { _controller: TEPlatformBundle:User:register }

te_user_profile:
    path:     /user/profile/{id}
    defaults: { _controller: TEPlatformBundle:Lift:profile }
    requirements:
      id:   \d

te_admin_removeLift:
    path:  /admin/remove/{id}
    defaults: { _controller: TEPlatformBundle:Lift:removeLift }
    requirements:
      id: \d

