services:
     redirect_register_user.registration.completed:
         class: TE\PlatformBundle\EventListener\RegistrationConfirmListener
         arguments: [@router]
         tags:
             - { name: kernel.event_subscriber }
