<?php

namespace TE\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookedPassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookedPassengerRepository extends EntityRepository
{
}
