<?php

namespace TE\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiftRepository extends EntityRepository
{
  public function findLiftByDate()
  {
    $qb = $this->createQueryBuilder('lift');

    $qb->Where('lift.dateLift > :date')
         ->setParameter('date', new \DateTime())
       ->orderBy('lift.dateLift', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

    public function findLiftByCity($fromCity, $toCity) {
        $qb = $this->createQueryBuilder('lift');

        $qb->Where('lift.fromCity == :fromCity')
            ->setParameter('fromCity', $fromCity)
           ->andWhere('lift.toCity == :toCity')
            ->setParameter('toCity', $toCity)
           ->andWhere('lift.dateLift > :date')
            ->setParameter('date', new \DateTime())
           ->orderBy('lift.dateLift', 'ASC')
        ;
    }
}
